### ISSUE TITLE
Do not hard-code Materials Project API key in ELATE code

### ISSUE THREAD

**Issue by dwinston** [coudertlab/elate#5]
Hi @fxcoudert ,

Please refactor `elastic.py` to not hard-code `mapiKey`. For example. you can set an environment variable `MAPI_KEY` and load it using `os.environ["MAPI_KEY"]` in the code. The ELATE integration with the Materials Project does not work right now because we had to revoke the key. These keys should not be shared publicly. Thank you for understanding, and thank you for maintaining this great project.

**Comment by fxcoudert** [comment]
Sorry about that, this line of code should not have made it into the Github repo. Will fix ASAP, and thanks for letting me know.

**Comment by fxcoudert** [comment]
Fixed in https://github.com/fxcoudert/elate/commit/f0a1b22c14864246f4949e5c5784c4667c159ed5

However, even after generating a new API key, my requests to Materials Project API return 403 error. Is there something more I need from you to get this running again @dwinston ?

**Comment by dwinston** [comment]
Thanks! I see in f0a1b22 that you remove the hard-coded key and add a mapiKey parameter to functions, but I do not see any code with modified calls that use e.g. `os.environ`. I also see that you previously used `base64.b64decode` to transform the key. It's difficult for me to debug without seeing all the code, but hopefully this helps?

**Comment by fxcoudert** [comment]
@dwinston the API key is now only stored in the server (whose code is not in a public repo), and passed as parameter. The API key is passed properly, but the requests end up 403. Did you block all API keys associated to my account?

**Comment by dwinston** [comment]
No, your API key should be fine. There's something weird going on with your `queryElasticityV2`. I also get a 403 error when I run it using my key, whereas I get results fine using e.g.

```python
import json
import requests

data = {
    'criteria': json.dumps({"task_id": "mp-2340"}),
    'properties': json.dumps(["formula", "pretty_formula", "material_id", "elasticity"]),
    'API_KEY': mapiKey
}
r = requests.post('https://materialsproject.org/rest/v2/query', data=data)
r.json()
```

Please try the above (`pip install requests`) to verify your API key.

**Comment by dwinston** [comment]
You certainly do not need to `urlencode` the data for the request -- perhaps this is the source of the error. I don't have much experience using the low-level `urllib.request` module - it appears that `requests` is [officially recommended](https://docs.python.org/3.7/library/urllib.request.html) (the "See also" block in the docs) as a higher-level interface, in case you are spending too much time debugging this.

**Comment by dwinston** [comment]
Also, I notice you have a function to get material IDs. There is a special route just for just this, if you want to use it, e.g.:

```python
import requests

query = "Fe2O3"

r = requests.get(f'https://materialsproject.org/rest/v2/materials/{query}/mids',
                 headers={"X-API-KEY": mapiKey})
r.json()
```

**Comment by fxcoudert** [comment]
@dwinston Thanks, I will debug it further, but what is very surprising is that it was working without issue until a few days ago

**Comment by fxcoudert** [comment]
`urllib` was having some issue, I fixed it and indeed `requests` is easier to deal with 👍
