### ISSUE TITLE
How to use the code locally?

### ISSUE THREAD

**Issue by hongyi-zhao** [coudertlab/elate#7]
How to use the code locally instead of calling it via the [web interface](https://progs.coudert.name/elate)?

Regards,
Zhao

**Comment by fxcoudert** [comment]
I've added a new Jupyter notebook, which explains how to use the code locally (without the website). You can find it at: https://github.com/coudertlab/elate/blob/master/tutorial.ipynb

It will be expanded and improved over time, and suggestions are welcome.

**Comment by hongyi-zhao** [comment]
I want to know why the last section of the tutorial is empty, as shown below:

![image](https://github.com/coudertlab/elate/assets/11155854/1bc7246a-2120-446d-977e-ae8327f41066)

**Comment by fxcoudert** [comment]
Because I have not finished it yet, it is a work in progress.

**Comment by hongyi-zhao** [comment]
BTW, what are the **high-dimensional properties** you mentioned here?

**Comment by fxcoudert** [comment]
I finished the notebook, it is now complete.
