### ISSUE TITLE
elastool vs elate.

### ISSUE THREAD

**Issue by hongyi-zhao** [coudertlab/elate#8]
Today, I noticed another similar tool named [`elastool`](https://github.com/zhongliliu/elastool), which seems to have more features than `elate`, but I'm unsure. Could you please give some objective comparisons and comments on the similarities and differences between these two tools?

Regards,
Zhao

**Comment by fxcoudert** [comment]
See the response by Elastool maintainer at https://github.com/zhongliliu/elastool/issues/5
